name: Deploy via SFTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SFTP Deploy to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 22
          source: "."  # carpeta local a subir
          target: "/ruta/remota/api"  # ruta en el servidor
          rm: false  # no borrar archivos previos
